import type { ModuleDef } from "@/types";

// Catálogo de módulos de la plataforma.
// Solo "agent" y "dashboard" son funcionales en Fase 1.
// El resto son placeholders honestos que muestran roadmap.
export const MODULES: ModuleDef[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    icon: "📊",
    href: "/dashboard",
    description: "Vista general de actividad, incidentes recientes y KPIs",
    status: "available",
    phase: 1,
    rolesAllowed: ["viewer", "consultor", "aprobador", "admin"],
  },
  {
    id: "agent",
    label: "Agente AMS",
    icon: "🤖",
    href: "/agent",
    description: "Chat con el agente IA. Diagnóstico, RCA y paso a paso SAP Supply Chain",
    status: "available",
    phase: 1,
    rolesAllowed: ["viewer", "consultor", "aprobador", "admin"],
  },
  {
    id: "history",
    label: "Historial",
    icon: "📜",
    href: "/history",
    description: "Listado de incidentes anteriores con filtros y detalle",
    status: "available",
    phase: 1,
    rolesAllowed: ["viewer", "consultor", "aprobador", "admin"],
  },
  {
    id: "knowledge",
    label: "Conocimiento",
    icon: "📚",
    href: "/knowledge",
    description: "Base de conocimiento documental con RAG. PDFs, Word, Excel, minutas",
    status: "available",
    phase: 2,
    rolesAllowed: ["consultor", "aprobador", "admin"],
  },
  {
    id: "tickets",
    label: "Tickets",
    icon: "🎫",
    href: "/tickets",
    description: "Conector Jira (real si hay credenciales) o mock de demo",
    status: "available",
    phase: 3,
    rolesAllowed: ["consultor", "aprobador", "admin"],
  },
  {
    id: "integrations",
    label: "Integraciones",
    icon: "🔌",
    href: "/integrations",
    description: "Webhooks salientes, Slack y Email para notificar eventos del agente",
    status: "available",
    phase: 3,
    rolesAllowed: ["aprobador", "admin"],
  },
  {
    id: "sap-readonly",
    label: "SAP Read-Only",
    icon: "🏭",
    href: "/sap-readonly",
    description: "Consultas a S/4HANA en modo lectura: OC, pedidos, materiales, movimientos. Mock o real",
    status: "available",
    phase: 4,
    rolesAllowed: ["aprobador", "admin"],
  },
  {
    id: "meetings",
    label: "Reuniones AMS",
    icon: "🎙️",
    href: "/meetings",
    description: "Sube audio, Whisper transcribe local, Gemini extrae minuta + acciones",
    status: "available",
    phase: 5,
    rolesAllowed: ["consultor", "aprobador", "admin"],
  },
  {
    id: "support-desk",
    label: "Mesa de Soporte",
    icon: "📞",
    href: "/support-desk",
    description: "Soporte AMS con IA de Nivel 1, escalación automática a Nivel 2 y KB curada",
    status: "available",
    phase: 7,
    rolesAllowed: ["consultor", "aprobador", "admin"],
  },
  {
    id: "voice-calls",
    label: "Canal Telefónico",
    icon: "☎️",
    href: "/voice-calls",
    description: "Llamadas entrantes atendidas por IA vía Twilio Voice. Transcripción + turnos USER/AI/SYSTEM, derivaciones a humano detectadas",
    status: "available",
    phase: 8,
    rolesAllowed: ["consultor", "aprobador", "admin"],
  },
  {
    id: "settings",
    label: "Configuración",
    icon: "⚙️",
    href: "/settings",
    description: "Cliente, ambiente y preferencias de la plataforma",
    status: "available",
    phase: 1,
    rolesAllowed: ["viewer", "consultor", "aprobador", "admin"],
  },
  {
    id: "mission-control",
    label: "Mission Control",
    icon: "🎮",
    href: "/mission-control",
    description: "Wallboard tipo NASA: SLA gauge, contadores en vivo, heatmap y feed de eventos. Pensado para proyectar en TV",
    status: "available",
    phase: 7,
    rolesAllowed: ["viewer", "consultor", "aprobador", "admin"],
  },
  {
    id: "topology",
    label: "Topology",
    icon: "🌍",
    href: "/topology",
    description: "Sistema nervioso en vivo: nodos del sistema + pulsos por cada evento real (incident, ticket, KB, reunión)",
    status: "available",
    phase: 7,
    rolesAllowed: ["viewer", "consultor", "aprobador", "admin"],
  },
  {
    id: "tv",
    label: "TV Mode",
    icon: "🎬",
    href: "/tv",
    description: "Slideshow auto-rotativo con 6 vistas. Modo presentación a clientes / sala de operaciones",
    status: "available",
    phase: 7,
    rolesAllowed: ["aprobador", "admin"],
  },
  {
    id: "demo",
    label: "Demo en vivo",
    icon: "🎬",
    href: "/demo",
    description: "Ejecuta un escenario end-to-end de la Mesa de Soporte con datos reales — pensado para mostrar a clientes",
    status: "available",
    phase: 7,
    rolesAllowed: ["consultor", "aprobador", "admin"],
  },
  {
    id: "executive",
    label: "Ejecutivo",
    icon: "🏢",
    href: "/executive",
    description: "Dashboard C-level: actividad, % IA, SLA, costo Gemini estimado y top clientes",
    status: "available",
    phase: 7,
    rolesAllowed: ["aprobador", "admin"],
  },
  {
    id: "admin",
    label: "Administración",
    icon: "🛡️",
    href: "/admin",
    description: "Gestión de usuarios y roles (solo admin)",
    status: "available",
    phase: 6,
    rolesAllowed: ["admin"],
  },
  {
    id: "war-room",
    label: "War Room",
    icon: "🌐",
    href: "/war-room",
    description: "Globo AMS Global Ops: clientes en el mapa con arcos animados por evento, KPIs holográficos y ticker en vivo",
    status: "available",
    phase: 8,
    rolesAllowed: ["aprobador", "admin"],
  },
  {
    id: "brain",
    label: "Agent Brain",
    icon: "🧠",
    href: "/brain",
    description: "Red neuronal del agente: cada interacción se propaga por triage → decision → resolver → output con señales animadas",
    status: "available",
    phase: 8,
    rolesAllowed: ["aprobador", "admin"],
  },
  {
    id: "terminal",
    label: "Bloomberg",
    icon: "📟",
    href: "/terminal",
    description: "Terminal estilo Bloomberg AMS: grid 4×3 con widgets vivos, log stream Matrix, sparklines y feed de eventos",
    status: "available",
    phase: 8,
    rolesAllowed: ["aprobador", "admin"],
  },
  {
    id: "hud",
    label: "Arc Reactor",
    icon: "⚛️",
    href: "/hud",
    description: "Cockpit estilo Iron Man: SLA en arc reactor, anillos giratorios, gauges holográficos, particle field y feed en pie",
    status: "available",
    phase: 8,
    rolesAllowed: ["aprobador", "admin"],
  },
  {
    id: "launchpad",
    label: "Launchpad",
    icon: "🚀",
    href: "/launchpad",
    description: "NASA mission control: boot sequence cinematográfica, countdown gigante, telemetry, waveform de tokens y launch demo con sonido",
    status: "available",
    phase: 8,
    rolesAllowed: ["aprobador", "admin"],
  },
  {
    id: "wallboard",
    label: "Wallboard 4K",
    icon: "🖥️",
    href: "/wallboard",
    description: "Quad-view sincronizado de las 4 visualizaciones para proyectar en TV 4K. Click para focus o auto-rotate cada 25s",
    status: "available",
    phase: 8,
    rolesAllowed: ["aprobador", "admin"],
  },
  {
    id: "forecast",
    label: "Forecast IA",
    icon: "🔮",
    href: "/forecast",
    description: "Proyección 7 días con regresión lineal sobre histórico real, banda de confianza 95%, anomalías detectadas y top 3 next-likely incidents",
    status: "available",
    phase: 8,
    rolesAllowed: ["aprobador", "admin"],
  },
  {
    id: "flow",
    label: "Data Flow",
    icon: "🌊",
    href: "/flow",
    description: "Río de partículas en vivo: cada evento real fluye por uno de 3 carriles (resolved/escalated/info), velocidad según RPM. Hover para aislar carril",
    status: "available",
    phase: 8,
    rolesAllowed: ["consultor", "aprobador", "admin"],
  },
  {
    id: "agent-lab",
    label: "Agent Lab",
    icon: "🧪",
    href: "/agent-lab",
    description: "Enseñá al agente: 👍/👎 a respuestas, replay & debug de conversaciones y casos por curar. Cada feedback humano alimenta la mejora continua del agente",
    status: "available",
    phase: 7,
    rolesAllowed: ["consultor", "aprobador", "admin"],
  },
  {
    id: "agent-training",
    label: "Entrenamiento IA",
    icon: "🎓",
    href: "/knowledge/training",
    description: "Centro de Entrenamiento del Agente: carga, valida, versiona y mejora el conocimiento del Agente AMS Supply Chain. Pipeline completo + simulador + brechas + Q&A",
    status: "available",
    phase: 7,
    rolesAllowed: ["consultor", "aprobador", "admin"],
  },
];

export function moduleById(id: string): ModuleDef | undefined {
  return MODULES.find((m) => m.id === id);
}
