// Seed data demo para Escalation N2.
// Todo ficticio. Se carga al primer uso si no hay datos en localStorage.

import type {
  EscalationRule, N2Responsible, EscalationRecord,
  ItsmConnectorConfig, EscalationSettings,
} from "@/types/escalation";

const NOW = "2026-05-30T10:00:00.000Z";

// ============================================================
// 5 responsables N2 demo
// ============================================================

export function buildSeedResponsibles(): N2Responsible[] {
  return [
    {
      id: "n2_maria",
      name: "María Fernández",
      email: "maria.fernandez@demo.cl",
      role: "N2_FUNCTIONAL_CONSULTANT",
      team: "AMS · Procure to Pay",
      sapModules: ["MM", "ARIBA"],
      processes: ["Procure to Pay", "Compras", "Recepción"],
      clients: ["Cliente Norte", "Cliente Sur"],
      countries: ["CL", "PE"],
      serviceLevels: ["STANDARD", "PREMIUM", "ENTERPRISE"],
      availabilityStatus: "AVAILABLE",
      workingHours: "08:00-18:00 CLT",
      timezone: "America/Santiago",
      maxActiveCases: 8,
      currentActiveCases: 3,
      skills: ["MIGO", "MIRO", "MM01", "ME21N", "Ariba P2P"],
      jiraAccountId: "557058:demo-maria",
      serviceNowUserId: "user.maria.demo",
      teamsUserId: "maria.fernandez@demo.cl",
      active: true,
      createdAt: NOW, updatedAt: NOW,
    },
    {
      id: "n2_carlos",
      name: "Carlos Rivas",
      email: "carlos.rivas@demo.cl",
      role: "N2_FUNCTIONAL_CONSULTANT",
      team: "AMS · Order to Cash",
      sapModules: ["SD"],
      processes: ["Order to Cash", "Ventas", "Facturación"],
      clients: ["Cliente Norte", "Cliente Andes"],
      countries: ["CL", "AR"],
      serviceLevels: ["PREMIUM", "ENTERPRISE"],
      availabilityStatus: "BUSY",
      workingHours: "09:00-19:00 CLT",
      timezone: "America/Santiago",
      maxActiveCases: 8,
      currentActiveCases: 7,
      skills: ["VA01", "VF01", "VL01N", "Pricing"],
      jiraAccountId: "557058:demo-carlos",
      serviceNowUserId: "user.carlos.demo",
      active: true,
      createdAt: NOW, updatedAt: NOW,
    },
    {
      id: "n2_daniela",
      name: "Daniela Soto",
      email: "daniela.soto@demo.cl",
      role: "N2_FUNCTIONAL_CONSULTANT",
      team: "AMS · Plan to Produce",
      sapModules: ["PP", "QM"],
      processes: ["Plan to Produce", "Quality Management"],
      clients: ["Cliente Industrial"],
      countries: ["CL"],
      serviceLevels: ["PREMIUM", "ENTERPRISE"],
      availabilityStatus: "AVAILABLE",
      workingHours: "08:00-17:00 CLT",
      timezone: "America/Santiago",
      maxActiveCases: 6,
      currentActiveCases: 2,
      skills: ["CO01", "CO11", "MRP", "QM01"],
      jiraAccountId: "557058:demo-daniela",
      serviceNowUserId: "user.daniela.demo",
      active: true,
      createdAt: NOW, updatedAt: NOW,
    },
    {
      id: "n2_andres",
      name: "Andrés Molina",
      email: "andres.molina@demo.cl",
      role: "N2_INTEGRATION_SPECIALIST",
      team: "AMS · Integraciones / BTP",
      sapModules: ["BTP", "INTEGRACION"],
      processes: ["Integrations", "Middleware", "IDocs"],
      clients: ["Cliente Norte", "Cliente Sur", "Cliente Industrial"],
      countries: ["CL", "PE", "AR"],
      serviceLevels: ["PREMIUM", "ENTERPRISE"],
      availabilityStatus: "ON_CALL",
      workingHours: "On-call 24/7",
      timezone: "America/Santiago",
      maxActiveCases: 10,
      currentActiveCases: 4,
      skills: ["BTP", "CPI", "IDoc", "OData", "REST", "ABAP Proxy"],
      jiraAccountId: "557058:demo-andres",
      serviceNowUserId: "user.andres.demo",
      active: true,
      createdAt: NOW, updatedAt: NOW,
    },
    {
      id: "n2_felipe",
      name: "Felipe Torres",
      email: "felipe.torres@demo.cl",
      role: "N2_SERVICE_LEAD",
      team: "AMS · Liderazgo",
      sapModules: ["MM", "SD", "PP", "QM", "BTP", "INTEGRACION", "EWM", "IBP"],
      processes: ["Todos"],
      clients: ["Cliente Norte", "Cliente Sur", "Cliente Industrial", "Cliente Andes"],
      countries: ["CL", "PE", "AR", "CO"],
      serviceLevels: ["STANDARD", "PREMIUM", "ENTERPRISE"],
      availabilityStatus: "AVAILABLE",
      workingHours: "08:00-20:00 CLT",
      timezone: "America/Santiago",
      maxActiveCases: 15,
      currentActiveCases: 5,
      skills: ["Liderazgo AMS", "RCA", "SLA management", "Stakeholders"],
      jiraAccountId: "557058:demo-felipe",
      serviceNowUserId: "user.felipe.demo",
      active: true,
      createdAt: NOW, updatedAt: NOW,
    },
  ];
}

// ============================================================
// 5 reglas demo
// ============================================================

export function buildSeedRules(): EscalationRule[] {
  return [
    {
      id: "rule_p1_prd",
      name: "P1 productivo → Líder N2",
      description: "Cualquier severidad CRÍTICA en ambiente productivo se deriva al Service Lead.",
      enabled: true,
      priority: 1,
      conditions: { severity: "P1", environment: "PRD" },
      targetLevel: 2,
      assignmentStrategy: "FIXED_PERSON",
      targetUserId: "n2_felipe",
      targetTeam: "AMS · Liderazgo",
      targetRole: "N2_SERVICE_LEAD",
      channel: "JIRA",
      slaMinutes: 30,
      requiresApproval: true,
      createdAt: NOW, updatedAt: NOW,
    },
    {
      id: "rule_mm_no_solution",
      name: "MM sin solución → Especialista MM",
      description: "Incidentes de MM sin solución encontrada por N1 → Daniela / María.",
      enabled: true,
      priority: 2,
      conditions: { sapModule: "MM", noSolutionFound: true },
      targetLevel: 2,
      assignmentStrategy: "BY_MODULE",
      targetTeam: "AMS · Procure to Pay",
      targetRole: "N2_FUNCTIONAL_CONSULTANT",
      channel: "JIRA",
      slaMinutes: 240,
      requiresApproval: false,
      createdAt: NOW, updatedAt: NOW,
    },
    {
      id: "rule_low_confidence",
      name: "Baja confianza del agente",
      description: "Si el agente respondió con confianza < 50 → revisión humana.",
      enabled: true,
      priority: 3,
      conditions: { confidenceBelow: 50 },
      targetLevel: 2,
      assignmentStrategy: "BY_AVAILABILITY",
      targetRole: "N2_FUNCTIONAL_CONSULTANT",
      channel: "MANUAL",
      slaMinutes: 480,
      requiresApproval: true,
      createdAt: NOW, updatedAt: NOW,
    },
    {
      id: "rule_integration_error",
      name: "Error técnico de integración",
      description: "Integraciones con IDoc/API/OData/RFC → Andrés (BTP).",
      enabled: true,
      priority: 2,
      conditions: {
        sapModule: "INTEGRACION",
        keywords: ["IDoc", "API", "OData", "RFC", "CPI"],
      },
      targetLevel: 2,
      assignmentStrategy: "FIXED_PERSON",
      targetUserId: "n2_andres",
      targetTeam: "AMS · Integraciones / BTP",
      targetRole: "N2_INTEGRATION_SPECIALIST",
      channel: "SERVICENOW",
      slaMinutes: 120,
      requiresApproval: false,
      createdAt: NOW, updatedAt: NOW,
    },
    {
      id: "rule_repeated_incident",
      name: "Incidentes repetidos",
      description: "Si el caso ya se repitió → escalar para análisis de fondo.",
      enabled: true,
      priority: 4,
      conditions: { repeatedIncident: true },
      targetLevel: 2,
      assignmentStrategy: "BY_WORKLOAD",
      targetRole: "N2_FUNCTIONAL_CONSULTANT",
      channel: "JIRA",
      slaMinutes: 360,
      requiresApproval: true,
      createdAt: NOW, updatedAt: NOW,
    },
  ];
}

// ============================================================
// 5 registros históricos demo
// ============================================================

export function buildSeedRecords(): EscalationRecord[] {
  return [
    {
      id: "esc_001",
      incidentId: "INC-2026-0042",
      escalationNumber: "ESC-2026-001",
      fromLevel: 1, toLevel: 2,
      reason: "P1 en PRD: MIGO bloqueado, recepciones detenidas en planta principal.",
      summary: "Incidente crítico: usuario reporta error M7 326 en MIGO al recepcionar OC 4500001234.\nÚltimo cambio relevante: parche SAP_BASIS aplicado anoche.\nValidaciones N1: documento MM existe, stock OK, usuario tiene autorización.\nN1 no logra resolver. Probable bug post-upgrade.",
      assignedTo: "n2_felipe",
      assignedToName: "Felipe Torres",
      assignedTeam: "AMS · Liderazgo",
      channel: "JIRA",
      ruleId: "rule_p1_prd",
      externalTicketId: "AMS-1042",
      externalTicketUrl: "https://jira.demo.local/browse/AMS-1042",
      status: "IN_PROGRESS_N2",
      slaTarget: "2026-05-30T11:30:00.000Z",
      slaMinutes: 30,
      createdBy: "u_consultor",
      approvedBy: "u_lider",
      approvedAt: "2026-05-30T09:45:00.000Z",
      requiresApproval: true,
      mode: "DEMO",
      events: [
        { type: "ESCALATION_CREATED",  at: "2026-05-30T09:30:00.000Z", by: "u_consultor", note: "Disparada por regla rule_p1_prd" },
        { type: "APPROVAL_REQUESTED",  at: "2026-05-30T09:31:00.000Z", by: "u_consultor" },
        { type: "APPROVED",            at: "2026-05-30T09:45:00.000Z", by: "u_lider" },
        { type: "SENT_TO_JIRA",        at: "2026-05-30T09:46:00.000Z", by: "system", note: "Ticket simulado AMS-1042 creado" },
        { type: "ASSIGNED_TO_N2",      at: "2026-05-30T09:47:00.000Z", by: "system", note: "Asignado a Felipe Torres" },
      ],
      createdAt: "2026-05-30T09:30:00.000Z",
      updatedAt: "2026-05-30T09:47:00.000Z",
    },
    {
      id: "esc_002",
      incidentId: "INC-2026-0040",
      escalationNumber: "ESC-2026-002",
      fromLevel: 1, toLevel: 2,
      reason: "IDoc DESADV detenido, integración con cliente Norte.",
      summary: "IDoc DESADV con estado 51 desde ayer 20:00. Cliente Norte reporta no haber recibido confirmaciones.\nMensaje: 'Date format error'. Probable cambio de mapping en CPI.",
      assignedTo: "n2_andres",
      assignedToName: "Andrés Molina",
      assignedTeam: "AMS · Integraciones / BTP",
      channel: "SERVICENOW",
      ruleId: "rule_integration_error",
      externalTicketId: "INC0012845",
      externalTicketUrl: "https://servicenow.demo.local/nav_to.do?uri=incident.do?sys_id=INC0012845",
      status: "RESOLVED_BY_N2",
      slaTarget: "2026-05-30T11:00:00.000Z",
      slaMinutes: 120,
      createdBy: "u_consultor",
      requiresApproval: false,
      mode: "DEMO",
      events: [
        { type: "ESCALATION_CREATED",   at: "2026-05-30T08:00:00.000Z", by: "u_consultor" },
        { type: "SENT_TO_SERVICENOW",   at: "2026-05-30T08:01:00.000Z", by: "system",     note: "Ticket simulado INC0012845" },
        { type: "ASSIGNED_TO_N2",       at: "2026-05-30T08:02:00.000Z", by: "system" },
        { type: "RESOLVED",             at: "2026-05-30T09:30:00.000Z", by: "n2_andres",  note: "Mapping CPI corregido, reproceso OK" },
      ],
      createdAt: "2026-05-30T08:00:00.000Z",
      updatedAt: "2026-05-30T09:30:00.000Z",
    },
    {
      id: "esc_003",
      incidentId: "INC-2026-0038",
      escalationNumber: "ESC-2026-003",
      fromLevel: 1, toLevel: 2,
      reason: "Baja confianza del agente sobre cálculo MRP.",
      summary: "Agente respondió con 38% de confianza ante consulta de MRP run para planta 1000.\nUsuario reporta resultados inesperados en MD04. Requiere validación funcional.",
      assignedTo: "n2_daniela",
      assignedToName: "Daniela Soto",
      assignedTeam: "AMS · Plan to Produce",
      channel: "MANUAL",
      ruleId: "rule_low_confidence",
      status: "ASSIGNED_TO_N2",
      slaTarget: "2026-05-31T07:00:00.000Z",
      slaMinutes: 480,
      createdBy: "u_consultor",
      approvedBy: "u_lider",
      approvedAt: "2026-05-30T07:15:00.000Z",
      requiresApproval: true,
      mode: "DEMO",
      events: [
        { type: "ESCALATION_CREATED",  at: "2026-05-30T07:00:00.000Z", by: "u_consultor" },
        { type: "APPROVAL_REQUESTED",  at: "2026-05-30T07:00:30.000Z", by: "u_consultor" },
        { type: "APPROVED",            at: "2026-05-30T07:15:00.000Z", by: "u_lider" },
        { type: "ASSIGNED_TO_N2",      at: "2026-05-30T07:20:00.000Z", by: "system" },
      ],
      createdAt: "2026-05-30T07:00:00.000Z",
      updatedAt: "2026-05-30T07:20:00.000Z",
    },
    {
      id: "esc_004",
      incidentId: "INC-2026-0030",
      escalationNumber: "ESC-2026-004",
      fromLevel: 1, toLevel: 2,
      reason: "MM repetido: tercera vez en una semana con mismo error de imputación CECO.",
      summary: "Usuario solicita facturar OC sin CeCo válido. Ya ocurrió 3 veces este mes.\nN1 resolvió las 3 veces con workaround, pero no se atacó el root cause.",
      assignedTo: "n2_maria",
      assignedToName: "María Fernández",
      assignedTeam: "AMS · Procure to Pay",
      channel: "JIRA",
      ruleId: "rule_repeated_incident",
      externalTicketId: "AMS-1031",
      externalTicketUrl: "https://jira.demo.local/browse/AMS-1031",
      status: "RESOLVED_BY_N2",
      slaTarget: "2026-05-26T13:00:00.000Z",
      slaMinutes: 360,
      createdBy: "u_consultor",
      approvedBy: "u_lider",
      approvedAt: "2026-05-26T07:30:00.000Z",
      requiresApproval: true,
      mode: "DEMO",
      events: [
        { type: "ESCALATION_CREATED", at: "2026-05-26T07:00:00.000Z", by: "u_consultor" },
        { type: "APPROVED",           at: "2026-05-26T07:30:00.000Z", by: "u_lider" },
        { type: "SENT_TO_JIRA",       at: "2026-05-26T07:31:00.000Z", by: "system" },
        { type: "RESOLVED",           at: "2026-05-27T15:00:00.000Z", by: "n2_maria", note: "Customizing OKB9 corregido, no se repite" },
      ],
      createdAt: "2026-05-26T07:00:00.000Z",
      updatedAt: "2026-05-27T15:00:00.000Z",
    },
    {
      id: "esc_005",
      incidentId: "INC-2026-0027",
      escalationNumber: "ESC-2026-005",
      fromLevel: 1, toLevel: 2,
      reason: "Consulta funcional SD: facturación masiva mensual.",
      summary: "Cliente solicita ejecución de VF06 con variante específica para cierre de mes.\nN1 escaló para validación de la variante con N2.",
      assignedTo: "n2_carlos",
      assignedToName: "Carlos Rivas",
      assignedTeam: "AMS · Order to Cash",
      channel: "JIRA",
      status: "RETURNED_TO_N1",
      slaTarget: "2026-05-25T15:00:00.000Z",
      slaMinutes: 240,
      createdBy: "u_consultor",
      requiresApproval: false,
      mode: "DEMO",
      events: [
        { type: "ESCALATION_CREATED",  at: "2026-05-25T11:00:00.000Z", by: "u_consultor" },
        { type: "SENT_TO_JIRA",        at: "2026-05-25T11:02:00.000Z", by: "system" },
        { type: "ASSIGNED_TO_N2",      at: "2026-05-25T11:05:00.000Z", by: "system" },
        { type: "RETURNED_TO_N1",      at: "2026-05-25T11:20:00.000Z", by: "n2_carlos", note: "Variante OK, devuelto a N1 con guía paso a paso." },
      ],
      createdAt: "2026-05-25T11:00:00.000Z",
      updatedAt: "2026-05-25T11:20:00.000Z",
    },
  ];
}

// ============================================================
// Conectores ITSM (modo DEMO por defecto)
// ============================================================

export function buildSeedConnectors(): ItsmConnectorConfig {
  return {
    jira: {
      enabled: true,
      mode: "DEMO",
      baseUrl: "https://jira.demo.local",
      projectKey: "AMS",
      issueType: "Incident",
      defaultPriority: "High",
      authConfigured: false,
      userEmail: "",
      apiTokenConfigured: false,
      defaultAssigneeAccountId: "",
      labels: ["ams", "sap", "nivel2"],
      components: ["SAP MM", "SAP SD", "SAP PP", "Integraciones"],
    },
    serviceNow: {
      enabled: true,
      mode: "DEMO",
      instanceUrl: "https://servicenow.demo.local",
      table: "incident",
      assignmentGroup: "SAP AMS N2",
      defaultPriority: "2",
      authConfigured: false,
      username: "",
      tokenConfigured: false,
    },
    sapCloudAlm: {
      enabled: false,
      mode: "FUTURE",
      endpoint: "",
      note: "Integración futura. Requiere licencia SAP Cloud ALM y conector backend.",
    },
    manualEnabled: true,
  };
}

// ============================================================
// Settings demo
// ============================================================

export function buildSeedSettings(): EscalationSettings {
  return {
    requiresApprovalDefault: true,
    allowAutoEscalationInDemo: false,
    defaultChannel: "JIRA",
    defaultTargetLevel: 2,
    slaBySeverity: {
      P1: 30,
      P2: 120,
      P3: 480,
      P4: 1440,
    },
    useAvailabilityForAssignment: true,
    useWorkloadForAssignment: true,
    notifyClientOnEscalation: true,
    autoCreateEscalationDocument: true,
    autoCreateKnowledgeIfResolved: true,
    autoCreateRcaIfCritical: true,
  };
}
