// Modelo de auditoría por ticket — timeline de eventos.
// Persistencia frontend en localStorage por demo. Sin backend en G1.

export type TicketAuditEventType =
  | "TICKET_CREATED"
  | "AUTO_ESTIMATE_GENERATED"
  | "ESTIMATE_RECALCULATED"
  | "MANUAL_ADJUSTMENT"
  | "TICKET_CLASSIFIED"
  | "AGENT_RESPONSE_GENERATED"
  | "KNOWLEDGE_MATCHED"
  | "SCOPE_ITEM_MATCHED"
  | "PLAYBOOK_RECOMMENDED"
  | "N2_ESCALATION_SUGGESTED"
  | "N2_ESCALATION_CREATED"
  | "JIRA_DEMO_CREATED"
  | "SERVICENOW_DEMO_CREATED"
  | "DOCUMENT_GENERATED"
  | "TEST_CASE_CREATED"
  | "QUALITY_EVALUATED"
  | "CONVERTED_TO_KNOWLEDGE"
  | "STATUS_CHANGED"
  | "COMMENT_ADDED"
  // Visual analysis
  | "VISUAL_EVIDENCE_ATTACHED"
  | "VISUAL_EVIDENCE_ANALYZED"
  | "TICKET_ESTIMATED_WITH_VISUAL_ANALYSIS"
  // Demo guiada end-to-end
  | "DEMO_STARTED"
  | "DEMO_STEP_COMPLETED"
  | "DEMO_COMPLETED"
  // Customer Response Intelligence
  | "CUSTOMER_RESPONSE_GENERATED"
  | "CUSTOMER_RESPONSE_QUALITY_CHECKED"
  | "CUSTOMER_RESPONSE_BLOCKED"
  | "CUSTOMER_RESPONSE_APPROVED"
  | "CUSTOMER_RESPONSE_SAVED"
  | "CUSTOMER_RESPONSE_SENT_MANUAL"
  // N2 Escalation Intelligence
  | "N2_INTELLIGENCE_ANALYZED"
  | "N2_INTELLIGENCE_VERDICT_ESCALATE"
  | "N2_INTELLIGENCE_VERDICT_STAY"
  // Knowledge Auto-Curation Intelligence
  | "KB_CURATION_CANDIDATE_PROPOSED"
  | "KB_CURATION_APPROVED"
  | "KB_CURATION_REJECTED"
  | "KB_CURATION_PUBLISHED";

export interface TicketAuditEvent {
  id: string;
  ticketId: string;
  eventType: TicketAuditEventType;
  title: string;
  description?: string;
  actor: string;          // nombre/email/system
  actorRole?: string;     // ADMIN, SERVICE_LEAD, etc.
  source: "ui" | "agent" | "system" | "integration";
  metadata?: Record<string, unknown>;
  createdAt: string;      // ISO timestamp
}

export const AUDIT_STORAGE = {
  events: "supply-chain-ams-ticket-audit-events",
} as const;

export const EVENT_LABELS: Record<TicketAuditEventType, string> = {
  TICKET_CREATED: "Ticket creado",
  AUTO_ESTIMATE_GENERATED: "Estimación generada",
  ESTIMATE_RECALCULATED: "Estimación recalculada",
  MANUAL_ADJUSTMENT: "Ajuste manual",
  TICKET_CLASSIFIED: "Clasificado con agente",
  AGENT_RESPONSE_GENERATED: "Respuesta del agente",
  KNOWLEDGE_MATCHED: "Conocimiento relacionado",
  SCOPE_ITEM_MATCHED: "Scope item relacionado",
  PLAYBOOK_RECOMMENDED: "Playbook recomendado",
  N2_ESCALATION_SUGGESTED: "Sugerido escalar a N2",
  N2_ESCALATION_CREATED: "Escalado a N2",
  JIRA_DEMO_CREATED: "Ticket Jira creado",
  SERVICENOW_DEMO_CREATED: "Ticket ServiceNow creado",
  DOCUMENT_GENERATED: "Documento generado",
  TEST_CASE_CREATED: "Caso de prueba",
  QUALITY_EVALUATED: "Evaluación de calidad",
  CONVERTED_TO_KNOWLEDGE: "Convertido en conocimiento",
  STATUS_CHANGED: "Estado cambiado",
  COMMENT_ADDED: "Comentario",
  VISUAL_EVIDENCE_ATTACHED: "Imagen adjuntada",
  VISUAL_EVIDENCE_ANALYZED: "Imagen analizada",
  TICKET_ESTIMATED_WITH_VISUAL_ANALYSIS: "Estimado con análisis visual",
  DEMO_STARTED: "Demo iniciada",
  DEMO_STEP_COMPLETED: "Paso demo completado",
  DEMO_COMPLETED: "Demo completada",
  CUSTOMER_RESPONSE_GENERATED: "Respuesta cliente generada",
  CUSTOMER_RESPONSE_QUALITY_CHECKED: "Quality gate evaluado",
  CUSTOMER_RESPONSE_BLOCKED: "Respuesta cliente bloqueada",
  CUSTOMER_RESPONSE_APPROVED: "Respuesta cliente aprobada",
  CUSTOMER_RESPONSE_SAVED: "Respuesta guardada en ticket",
  CUSTOMER_RESPONSE_SENT_MANUAL: "Respuesta enviada manualmente",
  N2_INTELLIGENCE_ANALYZED: "N2 Intelligence ejecutada",
  N2_INTELLIGENCE_VERDICT_ESCALATE: "N2 Intelligence: ESCALAR",
  N2_INTELLIGENCE_VERDICT_STAY: "N2 Intelligence: mantener en N1",
  KB_CURATION_CANDIDATE_PROPOSED: "Candidato KB propuesto auto",
  KB_CURATION_APPROVED: "Candidato KB aprobado",
  KB_CURATION_REJECTED: "Candidato KB rechazado",
  KB_CURATION_PUBLISHED: "KB publicado desde curación",
};

export const EVENT_ICONS: Record<TicketAuditEventType, string> = {
  TICKET_CREATED: "🎫",
  AUTO_ESTIMATE_GENERATED: "⏱",
  ESTIMATE_RECALCULATED: "↻",
  MANUAL_ADJUSTMENT: "✎",
  TICKET_CLASSIFIED: "🤖",
  AGENT_RESPONSE_GENERATED: "💬",
  KNOWLEDGE_MATCHED: "📚",
  SCOPE_ITEM_MATCHED: "🎯",
  PLAYBOOK_RECOMMENDED: "📕",
  N2_ESCALATION_SUGGESTED: "⚠",
  N2_ESCALATION_CREATED: "🚨",
  JIRA_DEMO_CREATED: "↗",
  SERVICENOW_DEMO_CREATED: "↗",
  DOCUMENT_GENERATED: "📄",
  TEST_CASE_CREATED: "🧪",
  QUALITY_EVALUATED: "🏅",
  CONVERTED_TO_KNOWLEDGE: "🧠",
  STATUS_CHANGED: "🔁",
  COMMENT_ADDED: "💭",
  VISUAL_EVIDENCE_ATTACHED: "📷",
  VISUAL_EVIDENCE_ANALYZED: "🔬",
  TICKET_ESTIMATED_WITH_VISUAL_ANALYSIS: "🎯",
  DEMO_STARTED: "🎬",
  DEMO_STEP_COMPLETED: "▶",
  DEMO_COMPLETED: "🏁",
  CUSTOMER_RESPONSE_GENERATED: "✉",
  CUSTOMER_RESPONSE_QUALITY_CHECKED: "🛡",
  CUSTOMER_RESPONSE_BLOCKED: "🚫",
  CUSTOMER_RESPONSE_APPROVED: "✅",
  CUSTOMER_RESPONSE_SAVED: "💾",
  CUSTOMER_RESPONSE_SENT_MANUAL: "📤",
  N2_INTELLIGENCE_ANALYZED: "🧠",
  N2_INTELLIGENCE_VERDICT_ESCALATE: "🚨",
  N2_INTELLIGENCE_VERDICT_STAY: "🔧",
  KB_CURATION_CANDIDATE_PROPOSED: "🧠",
  KB_CURATION_APPROVED: "✅",
  KB_CURATION_REJECTED: "✕",
  KB_CURATION_PUBLISHED: "📚",
};

export const EVENT_COLORS: Record<TicketAuditEventType, string> = {
  TICKET_CREATED: "#22d3ee",
  AUTO_ESTIMATE_GENERATED: "#a855f7",
  ESTIMATE_RECALCULATED: "#a855f7",
  MANUAL_ADJUSTMENT: "#fbbf24",
  TICKET_CLASSIFIED: "#10b981",
  AGENT_RESPONSE_GENERATED: "#10b981",
  KNOWLEDGE_MATCHED: "#22d3ee",
  SCOPE_ITEM_MATCHED: "#22d3ee",
  PLAYBOOK_RECOMMENDED: "#22d3ee",
  N2_ESCALATION_SUGGESTED: "#fbbf24",
  N2_ESCALATION_CREATED: "#ef4444",
  JIRA_DEMO_CREATED: "#5b8def",
  SERVICENOW_DEMO_CREATED: "#5b8def",
  DOCUMENT_GENERATED: "#a855f7",
  TEST_CASE_CREATED: "#a855f7",
  QUALITY_EVALUATED: "#fbbf24",
  CONVERTED_TO_KNOWLEDGE: "#10b981",
  STATUS_CHANGED: "#64748b",
  COMMENT_ADDED: "#64748b",
  VISUAL_EVIDENCE_ATTACHED: "#22d3ee",
  VISUAL_EVIDENCE_ANALYZED: "#a855f7",
  TICKET_ESTIMATED_WITH_VISUAL_ANALYSIS: "#10b981",
  DEMO_STARTED: "#fbbf24",
  DEMO_STEP_COMPLETED: "#22d3ee",
  DEMO_COMPLETED: "#10b981",
  CUSTOMER_RESPONSE_GENERATED: "#f59e0b",
  CUSTOMER_RESPONSE_QUALITY_CHECKED: "#22d3ee",
  CUSTOMER_RESPONSE_BLOCKED: "#ef4444",
  CUSTOMER_RESPONSE_APPROVED: "#10b981",
  CUSTOMER_RESPONSE_SAVED: "#a855f7",
  CUSTOMER_RESPONSE_SENT_MANUAL: "#10b981",
  N2_INTELLIGENCE_ANALYZED: "#22d3ee",
  N2_INTELLIGENCE_VERDICT_ESCALATE: "#ef4444",
  N2_INTELLIGENCE_VERDICT_STAY: "#10b981",
  KB_CURATION_CANDIDATE_PROPOSED: "#22d3ee",
  KB_CURATION_APPROVED: "#10b981",
  KB_CURATION_REJECTED: "#ef4444",
  KB_CURATION_PUBLISHED: "#a855f7",
};
