// 10 playbooks demo iniciales para arrancar.

import type { AmsPlaybook } from "@/types/ams-modules";

const NOW = "2026-05-29T10:00:00.000Z";

function uid(p: string, i: number) { return `${p}_${i.toString(36)}_${Math.random().toString(36).slice(2, 6)}`; }

function step(id: string, order: number, title: string, description: string, role = "Consultor AMS", min = 10, evidence = false): NonNullable<AmsPlaybook["steps"]>[number] {
  return {
    id, order, title, description, responsibleRole: role,
    estimatedMinutes: min, evidenceRequired: evidence,
    completionCriteria: "Paso completado y documentado",
  };
}

export function buildDefaultPlaybooks(): AmsPlaybook[] {
  return [
    {
      id: "pb_p1",
      title: "Incidente crítico P1 en productivo",
      description: "Procedimiento estándar para incidentes P1 que afectan operación.",
      sapModule: "AMS",
      process: "AMS Genérico",
      severity: "P1",
      triggerWhen: "Sistema productivo caído, transacción crítica bloqueada o impacto financiero/operacional inmediato.",
      steps: [
        step("s1", 1, "Convocar war-room", "Notificar a líder AMS + cliente + arquitecto + dueño del proceso.", "Service Lead", 5, true),
        step("s2", 2, "Aislar el impacto", "Confirmar el alcance: usuarios, módulos, transacciones afectadas. Comunicar.", "Consultor AMS", 10, false),
        step("s3", 3, "Aplicar workaround", "Implementar el workaround más rápido si existe.", "Consultor AMS", 30, true),
        step("s4", 4, "Investigar causa raíz", "Logs SM21, SM37, ST22, dumps + reproducción.", "Consultor técnico", 60, true),
        step("s5", 5, "Aplicar fix definitivo", "Coordinar con técnico ABAP / nota OSS / configuración.", "Service Lead", 120, true),
        step("s6", 6, "Validar con usuario", "Confirmación escrita del cliente que la operación volvió.", "Consultor AMS", 15, true),
        step("s7", 7, "RCA y cierre", "Documentar en Document Factory → RCA. Cerrar ticket.", "Service Lead", 45, true),
      ],
      requiredData: ["Hora de inicio", "Transacción afectada", "Cliente reportante", "Mensaje exacto"],
      responsibleRole: "Service Lead",
      slaTargetMinutes: 240,
      escalationRules: "Si en 30 min no hay workaround, escalar a Nivel 2. Si en 2h no hay solución definitiva, escalar a Director de Servicio.",
      evidenceRequired: ["Logs SM21/ST22", "Confirmación del usuario", "RCA firmado"],
      communicationTemplate: "Estimados, se ha detectado un incidente crítico en {sistema}. Estamos trabajando en el restablecimiento.",
      relatedKnowledgeItems: [],
      relatedScopeItems: [],
      status: "ACTIVE",
      version: "v1.0",
      owner: "Líder Servicio",
      createdAt: NOW, updatedAt: NOW,
      tags: ["P1", "crítico", "war-room"],
    },
    {
      id: "pb_mm_migo",
      title: "Error en entrada de mercancía MM",
      description: "MIGO no contabiliza contra OC.",
      sapModule: "MM",
      process: "Compras",
      severity: "P2",
      triggerWhen: "Usuario reporta error en MIGO al recibir mercancía.",
      steps: [
        step("s1", 1, "Pedir contexto", "Número de OC, centro, almacén, mensaje exacto.", "Consultor AMS", 5),
        step("s2", 2, "Validar ME23N", "Liberación de OC + posición no eliminada.", "Consultor AMS", 10, true),
        step("s3", 3, "Validar XK03", "Proveedor no bloqueado.", "Consultor AMS", 5),
        step("s4", 4, "Validar OMR6", "Tolerancias de cantidad/precio.", "Consultor AMS", 5),
        step("s5", 5, "Re-ejecutar MIGO", "Confirmar entrada y stock con MMBE.", "Consultor AMS", 5, true),
      ],
      requiredData: ["Nº OC", "Centro/Almacén", "Mensaje completo"],
      responsibleRole: "Consultor AMS",
      slaTargetMinutes: 60,
      escalationRules: "Si > 2 reintentos, escalar a consultor senior MM.",
      evidenceRequired: ["Captura del error", "Confirmación de la entrada"],
      communicationTemplate: "Hola, ya estamos revisando el caso de MIGO en {oc}.",
      relatedKnowledgeItems: ["kn_mm_migo_oc"], relatedScopeItems: ["J45"],
      status: "ACTIVE", version: "v1.0", owner: "Consultor AMS",
      createdAt: NOW, updatedAt: NOW, tags: ["MM", "MIGO", "OC"],
    },
    {
      id: "pb_sd_pricing",
      title: "Pedido de venta sin pricing SD",
      description: "VA01 no determina precio para condición PR00.",
      sapModule: "SD", process: "Ventas", severity: "P2",
      triggerWhen: "Usuario reporta error VPRICE 002 o pricing no determinado.",
      steps: [
        step("s1", 1, "Pedir datos", "Cliente, material, fecha, organización de ventas.", "Consultor AMS", 5),
        step("s2", 2, "Revisar V/08", "Estrategia de pricing del documento.", "Consultor AMS", 10),
        step("s3", 3, "Revisar VK13", "Registro vigente para la condición PR00.", "Consultor AMS", 10),
        step("s4", 4, "Revisar V/06 y V/04", "Acceso y grupo cliente/material.", "Consultor AMS", 15),
        step("s5", 5, "Crear/ajustar condición", "Crear registro VK11 si falta.", "Consultor AMS", 15, true),
      ],
      requiredData: ["Cliente", "Material", "Fecha"],
      responsibleRole: "Consultor AMS",
      slaTargetMinutes: 90,
      escalationRules: "Si involucra varias condiciones, escalar a SD senior.",
      evidenceRequired: ["Captura VK13", "Captura VA01 OK"],
      communicationTemplate: "Estamos revisando la configuración de pricing para {cliente}.",
      relatedKnowledgeItems: ["kn_sd_pricing"], relatedScopeItems: [],
      status: "ACTIVE", version: "v1.0", owner: "Consultor AMS",
      createdAt: NOW, updatedAt: NOW, tags: ["SD", "pricing", "VA01"],
    },
    {
      id: "pb_pp_mrp",
      title: "MRP no genera propuestas PP",
      description: "MD02/MD03 corre sin errores pero no genera órdenes.",
      sapModule: "PP", process: "Planificación", severity: "P3",
      triggerWhen: "Planificador reporta que MRP no genera propuestas.",
      steps: [
        step("s1", 1, "Revisar MM03 MRP1/MRP2", "Tipo y estrategia de planificación.", "Consultor PP", 10),
        step("s2", 2, "Revisar MD04", "Stock y necesidades brutas.", "Consultor PP", 10),
        step("s3", 3, "Revisar OMI8", "Parámetros del grupo MRP.", "Consultor PP", 10),
        step("s4", 4, "Logs SM37", "Revisar el último run y errores.", "Consultor PP", 10, true),
        step("s5", 5, "Re-ejecutar MD02", "Para el material y validar resultado.", "Consultor PP", 5),
      ],
      requiredData: ["Material", "Centro", "Fecha del último run"],
      responsibleRole: "Consultor PP",
      slaTargetMinutes: 120,
      escalationRules: "Si involucra MRP masivo, escalar a líder de Planificación.",
      evidenceRequired: ["Captura MD04", "Log SM37"],
      communicationTemplate: "Estamos revisando MRP del material {material}.",
      relatedKnowledgeItems: ["kn_pp_mrp"], relatedScopeItems: [],
      status: "ACTIVE", version: "v1.0", owner: "Consultor PP",
      createdAt: NOW, updatedAt: NOW, tags: ["PP", "MRP", "MD02"],
    },
    {
      id: "pb_int_idoc",
      title: "IDoc detenido en integración",
      description: "IDoc en status 51 o 64 sin procesar.",
      sapModule: "AMS", process: "Integraciones", severity: "P2",
      triggerWhen: "Sistema origen reporta que no recibe respuesta del IDoc.",
      steps: [
        step("s1", 1, "Identificar IDoc", "WE02 → buscar por sistema origen y fecha.", "Consultor AMS", 5),
        step("s2", 2, "Diagnosticar error", "Status 51 = error de aplicación, 64 = pendiente.", "Consultor AMS", 10),
        step("s3", 3, "Validar partner WE20", "Confirmar perfil y datos del partner.", "Consultor AMS", 5),
        step("s4", 4, "Validar segmento WE60", "Si error de sintaxis, revisar definición.", "Consultor AMS", 10),
        step("s5", 5, "Reprocesar WE19 / BD87", "Reprocesar IDoc manual o masivo.", "Consultor AMS", 5, true),
      ],
      requiredData: ["Nº IDoc", "Mensaje de error"],
      responsibleRole: "Consultor AMS",
      slaTargetMinutes: 90,
      escalationRules: "Si afecta cola completa, escalar a integraciones senior.",
      evidenceRequired: ["WE02 antes y después", "Log de reproceso"],
      communicationTemplate: "Estamos reprocesando los IDocs detenidos.",
      relatedKnowledgeItems: ["kn_int_idoc"], relatedScopeItems: [],
      status: "ACTIVE", version: "v1.0", owner: "Consultor AMS",
      createdAt: NOW, updatedAt: NOW, tags: ["IDoc", "WE02", "integración"],
    },
    {
      id: "pb_cierre_mes",
      title: "Cierre de mes con impacto logístico",
      description: "Coordinación entre Logística, MM, SD, FI durante el cierre.",
      sapModule: "AMS", process: "AMS Genérico", severity: "P2",
      triggerWhen: "Día -3 antes del cierre del mes.",
      steps: [
        step("s1", 1, "Notificar congelamiento", "Comunicar fecha y hora de freeze.", "Service Lead", 15, true),
        step("s2", 2, "Validar transacciones pendientes", "Listar OC sin recibir, OV sin facturar, MIGO pendientes.", "Consultor AMS", 30),
        step("s3", 3, "Cerrar período MM", "MMPV en la fecha planificada.", "Consultor MM", 10, true),
        step("s4", 4, "Cerrar período FI", "OB52 según calendario FI.", "Consultor FI", 10, true),
        step("s5", 5, "Validar consistencia", "Reportes de conciliación stock-FI.", "Consultor AMS", 60, true),
      ],
      requiredData: ["Calendario AMS", "Lista de centros activos"],
      responsibleRole: "Service Lead",
      slaTargetMinutes: 480,
      escalationRules: "Si hay diferencias > 1%, alertar al CFO.",
      evidenceRequired: ["Confirmación de cierre MM", "Confirmación FI", "Reporte de consistencia"],
      communicationTemplate: "Inicia procedimiento de cierre de período.",
      relatedKnowledgeItems: [], relatedScopeItems: [],
      status: "ACTIVE", version: "v1.0", owner: "Service Lead",
      createdAt: NOW, updatedAt: NOW, tags: ["cierre", "mes", "logística"],
    },
    {
      id: "pb_hypercare",
      title: "Hypercare post go-live",
      description: "Soporte intensivo durante las primeras 4 semanas post-implementación.",
      sapModule: "AMS", process: "AMS Genérico", severity: "P2",
      triggerWhen: "Primer día post go-live.",
      steps: [
        step("s1", 1, "Daily stand-up", "Reunión diaria de incidentes con cliente.", "Service Lead", 30, true),
        step("s2", 2, "Monitoreo proactivo", "Revisar dashboards de errores cada 2h.", "Consultor AMS", 30),
        step("s3", 3, "Atención priorizada", "Incidentes hypercare tienen SLA reducido 50%.", "Consultor AMS", 0),
        step("s4", 4, "Documentar lecciones", "Cada incidente debe generar KB o ajuste.", "Consultor AMS", 15, true),
        step("s5", 5, "Reporte semanal cliente", "Métricas + incidentes + plan.", "Service Lead", 60, true),
        step("s6", 6, "Cierre de hypercare", "Reunión formal con sponsor.", "Service Lead", 60, true),
      ],
      requiredData: ["Fecha de go-live", "Equipo hypercare", "Stakeholders cliente"],
      responsibleRole: "Service Lead",
      slaTargetMinutes: 30,
      escalationRules: "Cualquier P1 escala inmediatamente al sponsor del cliente.",
      evidenceRequired: ["Minutas diarias", "Reporte semanal", "Acta de cierre"],
      communicationTemplate: "Buen día, comienza el daily de hypercare. Estado actual: {estado}.",
      relatedKnowledgeItems: [], relatedScopeItems: [],
      status: "ACTIVE", version: "v1.0", owner: "Service Lead",
      createdAt: NOW, updatedAt: NOW, tags: ["hypercare", "go-live"],
    },
    {
      id: "pb_escalation_n2",
      title: "Escalamiento a Nivel 2",
      description: "Cuándo y cómo escalar un ticket a Nivel 2.",
      sapModule: "AMS", process: "AMS Genérico", severity: "P3",
      triggerWhen: "SLA consumida > 75%, 2 reintentos sin solución, o cliente VIP solicita.",
      steps: [
        step("s1", 1, "Revisar criterios", "Confirmar que aplica criterio de escalamiento.", "Consultor AMS", 5),
        step("s2", 2, "Preparar contexto", "Síntoma, reproducción, transacciones probadas, workaround, hipótesis.", "Consultor AMS", 20, true),
        step("s3", 3, "Crear ticket N2", "En la mesa de soporte con etiqueta ESCALATION_N2.", "Consultor AMS", 10, true),
        step("s4", 4, "Comunicar al cliente", "Notificar escalamiento + nuevo tiempo estimado.", "Consultor AMS", 10, true),
        step("s5", 5, "Seguimiento", "Estar disponible para info adicional.", "Consultor AMS", 0),
      ],
      requiredData: ["Síntoma", "Pasos probados", "Hipótesis"],
      responsibleRole: "Consultor AMS",
      slaTargetMinutes: 45,
      escalationRules: "Si N2 no responde en 4h, escalar a Service Lead.",
      evidenceRequired: ["Plantilla de escalamiento completa"],
      communicationTemplate: "Hola, hemos escalado tu caso a Nivel 2 con todo el contexto.",
      relatedKnowledgeItems: [], relatedScopeItems: [],
      status: "ACTIVE", version: "v1.0", owner: "Consultor AMS",
      createdAt: NOW, updatedAt: NOW, tags: ["escalamiento", "N2"],
    },
    {
      id: "pb_rca",
      title: "Generación de RCA",
      description: "Procedimiento para construir un Root Cause Analysis.",
      sapModule: "AMS", process: "AMS Genérico", severity: "P3",
      triggerWhen: "Tras resolver un incidente P1 o P2 con impacto.",
      steps: [
        step("s1", 1, "Recolectar evidencia", "Logs, screenshots, conversaciones, timestamps.", "Consultor AMS", 30, true),
        step("s2", 2, "Línea de tiempo", "Reconstruir hora por hora desde el primer síntoma.", "Consultor AMS", 30, true),
        step("s3", 3, "5 porqués", "Profundizar hasta llegar a la causa fundamental.", "Service Lead", 30),
        step("s4", 4, "Acciones correctivas", "Documentar fix aplicado.", "Service Lead", 15),
        step("s5", 5, "Acciones preventivas", "Plan para que no vuelva a ocurrir.", "Service Lead", 30, true),
        step("s6", 6, "Aprobación cliente", "Presentación formal del RCA.", "Service Lead", 60, true),
      ],
      requiredData: ["Incidente origen", "Equipo involucrado", "Métricas de impacto"],
      responsibleRole: "Service Lead",
      slaTargetMinutes: 480,
      escalationRules: "Si el cliente rechaza el RCA, escalar al Director.",
      evidenceRequired: ["RCA aprobado por cliente"],
      communicationTemplate: "Adjunto el RCA del incidente {codigo} para tu revisión.",
      relatedKnowledgeItems: ["kn_ams_rca"], relatedScopeItems: [],
      status: "ACTIVE", version: "v1.0", owner: "Service Lead",
      createdAt: NOW, updatedAt: NOW, tags: ["RCA", "post-mortem"],
    },
    {
      id: "pb_client_comm",
      title: "Comunicación formal al cliente",
      description: "Plantilla para comunicaciones críticas con sponsor del cliente.",
      sapModule: "AMS", process: "AMS Genérico", severity: "P3",
      triggerWhen: "Cualquier comunicación formal: status, incidente, milestone, riesgo.",
      steps: [
        step("s1", 1, "Definir audiencia", "¿Sponsor? ¿Equipo técnico? ¿Comité?", "Service Lead", 5),
        step("s2", 2, "Estructurar mensaje", "Asunto + contexto + hechos + plan + pedido.", "Service Lead", 20),
        step("s3", 3, "Validar tono", "Profesional, claro, sin tecnicismos innecesarios.", "Service Lead", 10),
        step("s4", 4, "Enviar y archivar", "Email + copia en sharepoint del proyecto.", "Service Lead", 5, true),
      ],
      requiredData: ["Audiencia", "Mensaje clave"],
      responsibleRole: "Service Lead",
      slaTargetMinutes: 60,
      escalationRules: "—",
      evidenceRequired: ["Email enviado"],
      communicationTemplate: "Estimado/a {sponsor},\n\nLe informamos sobre {tema}.\n\nSaludos cordiales,\nEquipo AMS",
      relatedKnowledgeItems: [], relatedScopeItems: [],
      status: "ACTIVE", version: "v1.0", owner: "Service Lead",
      createdAt: NOW, updatedAt: NOW, tags: ["comunicación", "cliente"],
    },
  ];
}
