// Datos demo del Centro de Entrenamiento del Agente.
// Reseteables por el usuario desde la pestaña Configuración → "Restaurar demo".

import type {
  KnowledgeItem, KnowledgeGap, TrainingVersion, TrainingSettings, TrainingQA,
} from "@/types/training";

const NOW = "2026-05-29T10:00:00.000Z";

export function buildDefaultKnowledgeItems(): KnowledgeItem[] {
  return [
    {
      id: "kn_mm_migo_oc",
      title: "MM · Entrada de mercancía no contabiliza contra OC",
      content:
        "## Síntoma\nAl ejecutar MIGO el sistema no permite contabilizar la entrada contra la OC.\n\n" +
        "## Posibles causas\n1. OC sin liberación.\n2. Posición de la OC eliminada.\n3. Proveedor bloqueado.\n4. Tolerancias de cantidad/precio fuera de rango.\n5. Mensaje M7 021 / 022 asociado.\n\n" +
        "## Solución paso a paso\n1. ME23N → verificar estrategia de liberación.\n2. Revisar `EKPO-LOEKZ` por posición eliminada.\n3. XK03 → tab Status verificar bloqueo de pagos/compras.\n4. OMR6 → tolerancias por grupo.\n5. SE91 → resolver mensaje M7 puntual.",
      summary: "MM no permite hacer MIGO contra una OC. Revisar liberación, posición eliminada, proveedor bloqueado, tolerancias y mensajes M7.",
      module: "MM",
      process: "Compras",
      type: "INCIDENT_SOLUTION",
      source: "ticket #MESA-1023",
      tags: ["MIGO", "OC", "M7", "liberación"],
      priority: "high",
      status: "PUBLISHED",
      score: 92,
      version: "v0.3",
      author: "Consultor AMS",
      createdAt: NOW,
      updatedAt: NOW,
      validatedBy: "Líder Servicio",
      publishedAt: NOW,
      validationStage: "FULLY_VALIDATED",
      functionalValidatedBy: "Consultor AMS",
      technicalValidatedBy: "Líder Servicio",
      rejectionReason: null,
    },
    {
      id: "kn_sd_pricing",
      title: "SD · Pedido de venta no determina precio",
      content:
        "## Mensaje\n`VPRICE 002 — No se pudo determinar precio para condición PR00`.\n\n" +
        "## Verificaciones\n1. V/08 → estrategia de pricing del documento.\n2. VK13 → registro vigente para combinación cliente/material.\n3. V/06 → acceso a condición.\n4. V/04 → grupo de cliente y material.",
      summary: "SD pricing no determina. Revisar V/08 estrategia, VK13 condición, V/06 acceso y V/04 grupos.",
      module: "SD",
      process: "Ventas",
      type: "KNOWN_ERROR",
      source: "minuta AMS 2026-05-12",
      tags: ["pricing", "VA01", "VK13", "PR00"],
      priority: "medium",
      status: "VALIDATED",
      score: 88,
      version: "v0.3",
      author: "Consultor AMS",
      createdAt: NOW,
      updatedAt: NOW,
      validatedBy: "Consultor AMS",
      publishedAt: null,
      validationStage: "FULLY_VALIDATED",
      functionalValidatedBy: "Consultor AMS",
      technicalValidatedBy: "Líder Servicio",
      rejectionReason: null,
    },
    {
      id: "kn_pp_mrp",
      title: "PP · MRP no genera propuestas para material",
      content:
        "## Síntoma\nMD02 / MD03 corre sin errores pero no genera órdenes planificadas.\n\n" +
        "## Diagnóstico AMS\n1. MM03 vista MRP1 → tipo de planificación.\n2. MM03 vista MRP2 → estrategia de planificación.\n3. MD04 → revisar stock y necesidades brutas.\n4. OMI8 → parámetros del grupo MRP.\n5. SM37 → revisar logs del último run.",
      summary: "MRP no genera propuestas. Revisar MM03 MRP1/MRP2, MD04, OMI8 y SM37 del job.",
      module: "PP",
      process: "Planificación",
      type: "AMS_PROCEDURE",
      source: "incidente recurrente",
      tags: ["MD02", "MRP", "MM03"],
      priority: "medium",
      status: "PENDING_REVIEW",
      score: 76,
      version: "v0.3",
      author: "Consultor AMS",
      createdAt: NOW,
      updatedAt: NOW,
      validatedBy: null,
      publishedAt: null,
      validationStage: "PENDING_FUNCTIONAL",
      functionalValidatedBy: null,
      technicalValidatedBy: null,
      rejectionReason: null,
    },
    {
      id: "kn_ewm_wt",
      title: "EWM · Tarea de almacén bloqueada en cola",
      content:
        "## Contexto\nLa tarea de almacén (WT) aparece en estado liberada pero no se confirma por RF.\n\n" +
        "## Pasos\n1. /SCWM/PRDO → identificar nro de WT.\n2. /SCWM/MON → cola del recurso.\n3. Liberar manual si no hay conflicto.",
      summary: "WT bloqueada en EWM. Revisar PRDO, monitor de colas y liberación manual del recurso.",
      module: "EWM",
      process: "Almacén",
      type: "FUNCTIONAL_STEP",
      source: "manual",
      tags: ["WT", "PRDO", "RF"],
      priority: "high",
      status: "DRAFT",
      score: 64,
      version: "v0.3",
      author: "Consultor AMS",
      createdAt: NOW,
      updatedAt: NOW,
      validatedBy: null,
      publishedAt: null,
      validationStage: "PENDING_FUNCTIONAL",
      functionalValidatedBy: null,
      technicalValidatedBy: null,
      rejectionReason: null,
    },
    {
      id: "kn_qm_lote",
      title: "QM · Lote de inspección sin decisión de empleo",
      content:
        "## Pregunta frecuente\n¿Por qué el material está bloqueado para uso si la inspección está completa?\n\n" +
        "## Respuesta\nFalta UD (Usage Decision). Ejecutar QA32 o QA11 para tomar la decisión y liberar el stock a calidad libre.",
      summary: "Lote QM con stock bloqueado: ejecutar QA32 / QA11 y registrar la UD.",
      module: "QM",
      process: "Calidad",
      type: "FAQ",
      source: "FAQ AMS",
      tags: ["QA32", "UD", "lote"],
      priority: "medium",
      status: "VALIDATED",
      score: 81,
      version: "v0.3",
      author: "Consultor AMS",
      createdAt: NOW,
      updatedAt: NOW,
      validatedBy: "Líder Servicio",
      publishedAt: null,
      validationStage: "FULLY_VALIDATED",
      functionalValidatedBy: "Consultor AMS",
      technicalValidatedBy: "Líder Servicio",
      rejectionReason: null,
    },
    {
      id: "kn_int_idoc",
      title: "Integraciones · IDoc detenido por error de segmento",
      content:
        "## Mensaje típico\n`EDI: Error de sintaxis en segmento E2EDP01`.\n\n" +
        "## Acciones\n1. WE02 → status 51 / 64.\n2. WE19 → reprocesar manualmente.\n3. WE60 → revisar definición del segmento.\n4. SM58 → cola tRFC.",
      summary: "IDoc detenido por error de segmento: WE02, WE19, WE60 y SM58 para diagnóstico y reproceso.",
      module: "AMS",
      process: "Integraciones",
      type: "KNOWN_ERROR",
      source: "incidente recurrente",
      tags: ["IDoc", "WE02", "EDI"],
      priority: "high",
      status: "PUBLISHED",
      score: 90,
      version: "v0.3",
      author: "Consultor AMS",
      createdAt: NOW,
      updatedAt: NOW,
      validatedBy: "Líder Servicio",
      publishedAt: NOW,
      validationStage: "FULLY_VALIDATED",
      functionalValidatedBy: "Consultor AMS",
      technicalValidatedBy: "Líder Servicio",
      rejectionReason: null,
    },
    {
      id: "kn_ams_rca",
      title: "AMS · Plantilla RCA para incidente crítico",
      content:
        "# Plantilla RCA AMS\n\n## 1. Resumen ejecutivo\n## 2. Línea de tiempo\n## 3. Impacto al negocio\n## 4. Causa raíz (5 porqués)\n## 5. Acciones correctivas inmediatas\n## 6. Acciones preventivas\n## 7. Métricas comprometidas",
      summary: "Plantilla RCA estándar AMS para incidentes críticos: 7 secciones obligatorias.",
      module: "AMS",
      process: "AMS Genérico",
      type: "RCA",
      source: "framework AMS",
      tags: ["RCA", "plantilla", "incidente crítico"],
      priority: "critical",
      status: "PUBLISHED",
      score: 95,
      version: "v0.3",
      author: "Líder Servicio",
      createdAt: NOW,
      updatedAt: NOW,
      validatedBy: "Admin Sistema",
      publishedAt: NOW,
      validationStage: "FULLY_VALIDATED",
      functionalValidatedBy: "Líder Servicio",
      technicalValidatedBy: "Admin Sistema",
      rejectionReason: null,
    },
    {
      id: "kn_btp_odata",
      title: "BTP · Revisión inicial de fallo en integración OData",
      content:
        "## Checklist\n1. BTP cockpit → status del destination.\n2. SCC4 → confirmar mandante origen.\n3. /IWFND/ERROR_LOG → revisar errores recientes.\n4. STRUST → certificados vigentes.\n5. RZ20 → CCMS de los servicios.",
      summary: "Fallo OData BTP: revisar destination, mandante, error log, certificados y CCMS.",
      module: "BTP",
      process: "Integraciones",
      type: "AMS_PROCEDURE",
      source: "manual",
      tags: ["BTP", "OData", "STRUST"],
      priority: "high",
      status: "PENDING_REVIEW",
      score: 79,
      version: "v0.3",
      author: "Consultor AMS",
      createdAt: NOW,
      updatedAt: NOW,
      validatedBy: null,
      publishedAt: null,
      validationStage: "PENDING_TECHNICAL",
      functionalValidatedBy: "Consultor AMS",
      technicalValidatedBy: null,
      rejectionReason: null,
    },
  ];
}

export function buildDefaultGaps(): KnowledgeGap[] {
  return [
    {
      id: "gap_ibp",
      title: "Falta procedimiento para error de forecast en SAP IBP",
      description: "Usuarios reportan errores recurrentes en cargas de forecast IBP y no hay procedimiento documentado.",
      module: "IBP",
      process: "Planificación",
      priority: "high",
      suggestedAction: "Cargar procedimiento de diagnóstico para errores de carga en planificación IBP y mapear códigos típicos.",
      status: "OPEN",
      createdAt: NOW,
      resolvedAt: null,
    },
    {
      id: "gap_ewm_rf",
      title: "Baja cobertura en EWM RF picking",
      description: "Solo hay un knowledge item de EWM y no cubre escenarios RF.",
      module: "EWM",
      process: "Almacén",
      priority: "medium",
      suggestedAction: "Crear guías paso a paso para RF picking, transferencias y conteo cíclico desde HU.",
      status: "OPEN",
      createdAt: NOW,
      resolvedAt: null,
    },
    {
      id: "gap_flexible_wf",
      title: "Sin guía validada para Flexible Workflow en compras",
      description: "El agente no tiene conocimiento aprobado sobre Flexible Workflow para liberación de OC.",
      module: "MM",
      process: "Compras",
      priority: "medium",
      suggestedAction: "Documentar configuración SWDD + escenarios de aprobación por monto.",
      status: "IN_PROGRESS",
      createdAt: NOW,
      resolvedAt: null,
    },
    {
      id: "gap_sd_pricing_rca",
      title: "Falta RCA para error recurrente de pricing SD",
      description: "Hay 3 incidentes en 30 días por el mismo síntoma SD pricing y no hay RCA.",
      module: "SD",
      process: "Ventas",
      priority: "high",
      suggestedAction: "Ejecutar RCA con líder funcional SD y publicar artículo con acciones preventivas.",
      status: "OPEN",
      createdAt: NOW,
      resolvedAt: null,
    },
  ];
}

export function buildDefaultVersions(): TrainingVersion[] {
  return [
    {
      id: "ver_v01",
      version: "v0.1",
      description: "Base inicial AMS — primer corpus de conocimiento del agente.",
      status: "ARCHIVED",
      itemCount: 12,
      validatedCount: 8,
      publishedCount: 8,
      createdBy: "Admin Sistema",
      createdAt: "2026-03-01T10:00:00.000Z",
      publishedAt: "2026-03-05T10:00:00.000Z",
      changelog: [
        "Carga inicial de 12 ítems base AMS",
        "Cobertura MM, SD, AMS genérico",
      ],
    },
    {
      id: "ver_v02",
      version: "v0.2",
      description: "Conocimiento MM/SD — expansión cobertura procesos críticos.",
      status: "ARCHIVED",
      itemCount: 22,
      validatedCount: 18,
      publishedCount: 15,
      createdBy: "Líder Servicio",
      createdAt: "2026-04-10T10:00:00.000Z",
      publishedAt: "2026-04-15T10:00:00.000Z",
      changelog: [
        "Añadidos 10 ítems MM y SD",
        "Validación funcional + técnica activada",
        "Score promedio subió de 71 → 84",
      ],
    },
    {
      id: "ver_v03",
      version: "v0.3",
      description: "Validación AMS premium — incorpora EWM, QM, integraciones, BTP.",
      status: "PUBLISHED",
      itemCount: 8,
      validatedCount: 5,
      publishedCount: 3,
      createdBy: "Líder Servicio",
      createdAt: NOW,
      publishedAt: NOW,
      changelog: [
        "Incorpora EWM + QM + IDoc + BTP",
        "Activado modo estricto anti-alucinación",
        "Plantilla RCA crítica publicada",
      ],
    },
  ];
}

export function buildDefaultQA(): TrainingQA[] {
  return [
    {
      id: "qa_mm_1",
      knowledgeItemId: "kn_mm_migo_oc",
      question: "No puedo hacer MIGO contra una OC. ¿Qué reviso?",
      expectedAnswer: "Primero verifica liberación en ME23N, que la posición no esté eliminada, que el proveedor no esté bloqueado en XK03, las tolerancias en OMR6 y mensajes M7 con SE91.",
      approved: true,
      createdAt: NOW,
    },
    {
      id: "qa_sd_1",
      knowledgeItemId: "kn_sd_pricing",
      question: "VA01 no determina precio para PR00. ¿Qué pasos sigo?",
      expectedAnswer: "Revisa V/08 (estrategia), VK13 (condición vigente), V/06 (acceso) y V/04 (grupo cliente/material).",
      approved: true,
      createdAt: NOW,
    },
    {
      id: "qa_int_1",
      knowledgeItemId: "kn_int_idoc",
      question: "Tengo IDocs en status 51 por error de segmento. ¿Cómo procedo?",
      expectedAnswer: "Inspecciona en WE02, reprocesa con WE19, valida la definición con WE60 y revisa cola tRFC con SM58.",
      approved: true,
      createdAt: NOW,
    },
  ];
}

export function buildDefaultSettings(): TrainingSettings {
  return {
    minScoreToPublish: 80,
    requireFunctionalValidation: true,
    requireTechnicalValidation: true,
    allowAutoPublish: false,
    activeModules: ["MM", "SD", "PP", "EWM", "QM", "AMS", "BTP"],
    mainLanguage: "es",
    responseFormat: "structured",
    versionRetention: 10,
    strictMode: true,
  };
}
